name: Release Build Win64

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12.15.0

      - name: Install Node modules
        run: npm install

      - name: Make build
        run: npm run build-win64
        
      - name: Get name from package.json
        run: |
          test -n "$(node -p -e "require('./package.json').name")" &&
          echo "::set-env name=PACKAGE_NAME::$(node -p -e "require('./package.json').name")" || exit 1

      - name: Get version from package.json
        run: |
          test -n "$(node -p -e "require('./package.json').version")" &&
          echo "::set-env name=PACKAGE_VERSION::$(node -p -e "require('./package.json').version")" || exit 1

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-win64.7z
          asset_path: ./_builds/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}-win64.7z
          asset_content_type: application/x-7z-compressed 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
